import turtle
#from codigo_fuente import *
#from codigo_fuente import p_adv
"defs"

lapiz = turtle.Turtle()
lapiz.shape()
lapiz.speed(5)
turtle.bgcolor("lightblue") #sin el turtle no cambia el background color de la ventana, no se por que tira error. no debería... pero funciona :D

def landscape(): #dibujo del landscape
    turtle.setup(width=1200, height=1200, startx=None, starty=None)
    lapiz.speed(0)
    lapiz.penup()
    lapiz.color("green")
    lapiz.goto(-600,300)
    lapiz.width(1)
    lapiz.pendown()
    lapiz.begin_fill()
    i=0
    while(i<2):
        lapiz.forward(1200)
        lapiz.right(90)
        lapiz.forward(1200)
        lapiz.right(90)
        i+=1
    lapiz.end_fill()

    #dibujar fogata
    lapiz.penup()
    lapiz.goto(60,0)
    lapiz.color("red")
    lapiz.width(2)
    lapiz.pendown()
    lapiz.begin_fill()
    lapiz.forward(35)
    lapiz.left(90)
    lapiz.forward(50)
    lapiz.left(135)
    lapiz.forward(20)
    lapiz.right(90)
    lapiz.forward(20)
    lapiz.left(90)
    lapiz.forward(20)
    lapiz.left(45)
    lapiz.forward(36)
    lapiz.end_fill()

    #dibujar arbol
    lapiz.penup()
    lapiz.goto(200,0)
    lapiz.setheading(0)
    lapiz.color("brown")
    lapiz.pendown()
    lapiz.begin_fill()
    lapiz.left(90)
    lapiz.forward(600)
    lapiz.right(90)
    lapiz.forward(20)
    lapiz.right(90)
    lapiz.forward(600)
    lapiz.right(90)
    lapiz.end_fill()
    lapiz.penup()
    lapiz.right(90)
    lapiz.forward(270)
    lapiz.left(90)
    lapiz.pendown()
    lapiz.forward(150)

    #escrituras de la ciudad
    lapiz.setheading(0)
    lapiz.color("yellow")
    lapiz.left(-90)
    lapiz.forward(20)
    lapiz.begin_fill()
    lapiz.left(90)
    lapiz.forward(20)
    lapiz.left(90)
    lapiz.forward(10)
    lapiz.left(90)
    lapiz.forward(40)
    lapiz.left(90)
    lapiz.forward(10)
    lapiz.left(90)
    lapiz.forward(10)
    lapiz.end_fill()

    lapiz.penup() #dibujar leños


    lapiz.penup() #dibuja el corazon que indica las vidas
    lapiz.goto(540,500) #al vajar las vidas se cambia el numero del corazon
    lapiz.speed(0)
    lapiz.pendown()
    lapiz.begin_fill()
    lapiz.pensize(3)
    lapiz.color("red")
    lapiz.left(50)
    lapiz.forward(53)
    lapiz.circle(20,200)
    lapiz.right(140)
    lapiz.circle(20,200)
    lapiz.forward(53)
    lapiz.end_fill()

def dibujar_ladron():
    lapiz.speed(0)
    lapiz.width(5)
    lapiz.hideturtle()
    lapiz.penup()
    lapiz.goto(400,100)
    lapiz.setheading(0) #setea donde mira el lapiz a default
    lapiz.pendown()
    lapiz.color("black")
    lapiz.circle(25)
    lapiz.left(-70)
    lapiz.forward(30)
    lapiz.left(-10)
    lapiz.forward(40)
    lapiz.left(270)
    lapiz.forward(50)
    lapiz.left(90)
    lapiz.forward(50)
    lapiz.backward(50)
    lapiz.right(90)
    lapiz.backward(50)
    lapiz.left(10)
    lapiz.forward(50)
    lapiz.left(50)
    lapiz.forward(50)
    lapiz.backward(50)
    lapiz.left(-50)
    lapiz.backward(50)
    lapiz.left(80)
    lapiz.backward(40)
    lapiz.right(120)
    lapiz.forward(60)
    lapiz.width(1)

def intro_sherif(): #animacion sherif parte 1
    lapiz.penup()
    lapiz.setheading(0)
    lapiz.goto(-300,100)
    lapiz.speed(0)  
    lapiz.color("orange") #setea color a naranjo
    lapiz.pendown()
    lapiz.width(10)
    lapiz.circle(30) #cabeza
    lapiz.right(90) #     |
    lapiz.forward(80) #   v cuerpo
    lapiz.left(45)
    lapiz.forward(80)
    lapiz.right(180)
    lapiz.forward(80)
    lapiz.left(90)
    lapiz.forward(80)   
    lapiz.penup()   
    lapiz.goto(-300,75)   
    lapiz.pendown() 
    lapiz.forward(50)
    lapiz.left(180)
    lapiz.forward(50)
    lapiz.right(45)
    lapiz.forward(50)   
    lapiz.penup() #dejar de dibujar
    lapiz.color("black") #color de letras
    lapiz.goto(-250,150)
    lapiz.speed(1)
    lapiz.width(1)
    lapiz.pendown()
    lapiz.write("NOOOO LADRÓN QUE HACES!!!", True, font=("arial", 10)) #frase que escribe, True para hacer un pequeño delay, font para fuente y tamaño
    lapiz.speed(0)
    lapiz.clear()
    #parte 2 de animacion
    landscape() #redibujar landscape
    
    lapiz.setheading(0)
    lapiz.penup()
    lapiz.goto(-300,100) 
    lapiz.speed(0)
    lapiz.pendown() 
    lapiz.color("orange")
    lapiz.width(10)
    lapiz.circle(30)
    lapiz.right(90)
    lapiz.forward(80)
    lapiz.left(45)
    lapiz.forward(70)
    lapiz.right(180)
    lapiz.forward(70)
    lapiz.left(110)
    lapiz.forward(60)   
    lapiz.penup()   
    lapiz.goto(-300,75)   
    lapiz.pendown() 
    lapiz.forward(50)
    lapiz.left(180)
    lapiz.forward(50)
    lapiz.right(45)
    lapiz.forward(20)
    lapiz.left(90)
    lapiz.forward(20)   

def sherif_acepto_reto():
    lapiz.setheading(0)
    lapiz.penup()
    lapiz.speed(0)
    lapiz.color("black")
    lapiz.goto(-250,150)
    lapiz.speed(1)
    lapiz.width(1)
    lapiz.pendown()
    lapiz.write("Hmmm...", True, font=("arial",10))
    lapiz.undo()
    lapiz.write("No queda de otra", True, font=("arial", 10))
    lapiz.undo()
    lapiz.write("Comencemos...", True, font=("arial", 10))
    lapiz.undo()

def animacion_ladron(): #animacion ladron
    lapiz.width(5)
    lapiz.hideturtle()
    lapiz.penup()
    lapiz.goto(400,100)
    lapiz.setheading(0) #setea donde mira el lapiz a default
    lapiz.pendown()
    lapiz.color("black")
    lapiz.circle(25)
    lapiz.left(-70)
    lapiz.forward(30)
    lapiz.left(-10)
    lapiz.forward(40)
    lapiz.left(270)
    lapiz.forward(50)
    lapiz.left(90)
    lapiz.forward(50)
    lapiz.backward(50)
    lapiz.right(90)
    lapiz.backward(50)
    lapiz.left(10)
    lapiz.forward(50)
    lapiz.left(50)
    lapiz.forward(50)
    lapiz.backward(50)
    lapiz.left(-50)
    lapiz.backward(50)
    lapiz.left(80)
    lapiz.backward(40)
    lapiz.right(120)
    lapiz.forward(60)
    lapiz.width(1)
    # lapiz.color("pink") #escrituras de la ciudad
    # lapiz.setheading(-90)
    # lapiz.forward(20)
    # lapiz.begin_fill()
    # lapiz.left(90)
    # lapiz.forward(20)
    # lapiz.left(90)
    # lapiz.forward(10)
    # lapiz.left(90)
    # lapiz.forward(40)
    # lapiz.left(90)
    # lapiz.forward(10)
    # lapiz.left(90)
    # lapiz.forward(10)
    # lapiz.end_fill()

    lapiz.penup()
    lapiz.goto(250,160)
    lapiz.speed(2)
    lapiz.color("black")

    #dialogo
    lapiz.pendown()
    lapiz.write("Quieres esto?. . .", True, font=("arial", 10))
    lapiz.undo()
    #cuadro blanco para borrar
    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.speed(3)
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("SOLVE MY READLE!!!", True, font=("arial", 10))
    lapiz.undo()
    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(170,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("Tienes que adivinar la frace que estoy pensando...", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(170,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("Tienes 6 intentos", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("Sinó... pues", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("You y tu town say bye bye ", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("MUAJAJAJAJAJA!!!!", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    sherif_acepto_reto()

def animacion_fuego(malas):
    if(malas==1):
        lapiz.speed(0)
        lapiz.penup()
        lapiz.goto(60,0)
        lapiz.color("red")
        lapiz.width(2)
        lapiz.setheading(0)
        lapiz.pendown()
        lapiz.begin_fill()
        lapiz.forward(35)
        lapiz.left(90)
        lapiz.forward(70)#cambiante segun malas
        lapiz.left(135)
        lapiz.forward(20)
        lapiz.right(90)
        lapiz.forward(20)
        lapiz.left(90)
        lapiz.forward(20)
        lapiz.left(45)
        lapiz.forward(56)#cambiante segun malas
        lapiz.end_fill()
    if(malas==2):
        lapiz.speed(0)
        lapiz.penup()
        lapiz.goto(60,0)
        lapiz.color("red")
        lapiz.width(2)
        lapiz.setheading(0)
        lapiz.pendown()
        lapiz.begin_fill()
        lapiz.forward(35)
        lapiz.left(90)
        lapiz.forward(110)#cambiante segun malas
        lapiz.left(135)
        lapiz.forward(20)
        lapiz.right(90)
        lapiz.forward(20)
        lapiz.left(90)
        lapiz.forward(20)
        lapiz.left(45)
        lapiz.forward(86)#cambiante segun malas
        lapiz.end_fill()
    if(malas==3):
        lapiz.speed(0)
        lapiz.penup()
        lapiz.goto(60,0)
        lapiz.color("red")
        lapiz.width(2)
        lapiz.setheading(0)
        lapiz.pendown()
        lapiz.begin_fill()
        lapiz.forward(35)
        lapiz.left(90)
        lapiz.forward(150)#cambiante segun malas
        lapiz.left(135)
        lapiz.forward(20)
        lapiz.right(90)
        lapiz.forward(20)
        lapiz.left(90)
        lapiz.forward(20)
        lapiz.left(45)
        lapiz.forward(136)#cambiante segun malas
        lapiz.end_fill()
    if(malas==4):
        lapiz.speed(0)
        lapiz.penup()
        lapiz.goto(60,0)
        lapiz.color("red")
        lapiz.width(2)
        lapiz.setheading(0)
        lapiz.pendown()
        lapiz.begin_fill()
        lapiz.forward(35)
        lapiz.left(90)
        lapiz.forward(200)#cambiante segun malas
        lapiz.left(135)
        lapiz.forward(20)
        lapiz.right(90)
        lapiz.forward(20)
        lapiz.left(90)
        lapiz.forward(20)
        lapiz.left(45)
        lapiz.forward(186)#cambiante segun malas
        lapiz.end_fill()
    if(malas==5):
        lapiz.speed(0)
        lapiz.penup()
        lapiz.goto(60,0)
        lapiz.color("red")
        lapiz.width(2)
        lapiz.setheading(0)
        lapiz.pendown()
        lapiz.begin_fill()
        lapiz.forward(35)
        lapiz.left(90)
        lapiz.forward(240)#cambiante segun malas
        lapiz.left(135)
        lapiz.forward(20)
        lapiz.right(90)
        lapiz.forward(20)
        lapiz.left(90)
        lapiz.forward(20)
        lapiz.left(45)
        lapiz.forward(226)#cambiante segun malas
        lapiz.end_fill()
    if(malas==6):
        lapiz.speed(0)
        lapiz.penup()
        lapiz.goto(60,0)
        lapiz.color("red")
        lapiz.width(2)
        lapiz.setheading(0)
        lapiz.pendown()
        lapiz.begin_fill()
        lapiz.forward(35)
        lapiz.left(90)
        lapiz.forward(270)#cambiante segun malas
        lapiz.left(135)
        lapiz.forward(20)
        lapiz.right(90)
        lapiz.forward(20)
        lapiz.left(90)
        lapiz.forward(20)
        lapiz.left(45)
        lapiz.forward(256)#cambiante segun malas
        lapiz.end_fill()
        #llamar animacion de final (loss)

def intro_anim(): #llama a las otras animaciones para la introduccion
    landscape()
    dibujar_ladron()
    intro_sherif()
    animacion_ladron()
    vida=6 #vidas iniciales
    vidas(vida)

def entradas(): #muestra ventana para ingresar letras
    letra=turtle.textinput("", "ingrese una letra (solo una a la vez): ") 
    if(len(letra)<0):
        turtle.textinput("entrada invalida", "ingrese UNA letra: ") #en caso de que ingresen algo diferente se recalca UNA letra
        return letra #haga o no haga caso el jugador se returna lo que haya ingresado
    else:
        return letra

def vidas(vida):
    lapiz.speed(0)
    lapiz.penup()
    lapiz.goto(532,525)
    lapiz.pendown()
    lapiz.setheading(0)
    lapiz.color("red")
    lapiz.begin_fill()
    lapiz.forward(30)
    lapiz.left(90)
    lapiz.forward(40)
    lapiz.left(90)
    lapiz.forward(30)
    lapiz.left(90)
    lapiz.forward(40)
    lapiz.left(90)
    lapiz.end_fill()
    lapiz.color("white")
    lapiz.write(vida,False, font=("jellee",25))

def animacion_gana():
    lapiz.penup()
    lapiz.goto(250,160)
    lapiz.color("black")
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("Ganó esta vez, sheriff...", True, font=("arial",10))
    lapiz.undo()

def animacion_pierde():
    lapiz.penup()
    lapiz.goto(250,160)
    lapiz.color("black")
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("Perdió, sheriff, y el pueblo con usted", True, font=("arial",10))
    lapiz.undo()