import turtle
#from codigo_fuente import p_adv

lapiz = turtle.Turtle()
lapiz.shape()
lapiz.speed(5)
turtle.bgcolor("lightblue") #sin el turtle no cambia el background color de la ventana

def landscape(): #dibujo del landscape
    lapiz.speed(0)
    lapiz.penup()
    lapiz.color("green")
    lapiz.goto(-600,200)
    lapiz.width(1)
    lapiz.pendown()
    lapiz.begin_fill()
    i=0
    while(i<2):
        lapiz.forward(1200)
        lapiz.right(90)
        lapiz.forward(1200)
        lapiz.right(90)
        i+=1
    lapiz.end_fill()    

    #dibujar fogata
    lapiz.penup()
    lapiz.goto(-150,0)
    lapiz.color("brown")
    lapiz.pendown()


def intro_sherif(): #animacion sherif parte 1
    lapiz.penup()
    lapiz.setheading(0)
    lapiz.goto(-300,100)
    lapiz.speed(0)  
    lapiz.color("orange") #setea color a naranjo
    lapiz.pendown()
    lapiz.width(10)
    lapiz.circle(30) #cabeza
    lapiz.right(90) #     |
    lapiz.forward(80) #   v cuerpo
    lapiz.left(45)
    lapiz.forward(80)
    lapiz.right(180)
    lapiz.forward(80)
    lapiz.left(90)
    lapiz.forward(80)   
    lapiz.penup()   
    lapiz.goto(-300,75)   
    lapiz.pendown() 
    lapiz.forward(50)
    lapiz.left(180)
    lapiz.forward(50)
    lapiz.right(45)
    lapiz.forward(50)   
    lapiz.penup() #dejar de dibujar
    lapiz.color("black") #color de letras
    lapiz.goto(-250,150)
    lapiz.speed(1)
    lapiz.width(1)
    lapiz.pendown()
    lapiz.write("NOOOO LADRÓN QUE HACES!!!", True, font=("arial", 10)) #frase que escribe, True para hacer un pequeño delay, font para fuente y tamaño
    lapiz.speed(0)
    lapiz.clear()
    #parte 2 de animacion
    landscape() #redibujar landscape

    lapiz.penup()
    lapiz.goto(-300,100) 
    lapiz.speed(0)
    lapiz.pendown() 
    lapiz.color("orange")
    lapiz.width(10)
    lapiz.circle(30)
    lapiz.right(90)
    lapiz.forward(80)
    lapiz.left(45)
    lapiz.forward(70)
    lapiz.right(180)
    lapiz.forward(70)
    lapiz.left(110)
    lapiz.forward(60)   
    lapiz.penup()   
    lapiz.goto(-300,75)   
    lapiz.pendown() 
    lapiz.forward(50)
    lapiz.left(180)
    lapiz.forward(50)
    lapiz.right(45)
    lapiz.forward(20)
    lapiz.left(90)
    lapiz.forward(20)   

def sherif_acepto_reto():
    lapiz.penup()
    lapiz.speed(0)
    lapiz.color("black")
    lapiz.goto(-250,150)
    lapiz.speed(1)
    lapiz.width(1)
    lapiz.pendown()
    lapiz.write("Hmmm...", True, font=("arial",10))
    lapiz.undo()
    lapiz.write("No queda de otra", True, font=("arial", 10))
    lapiz.undo()
    lapiz.write("Comencemos...", True, font=("arial", 10))

def animacion_ladron(): #animacion ladron
    lapiz.width(5)
    lapiz.hideturtle()
    lapiz.penup()
    lapiz.goto(400,100)
    lapiz.setheading(0) #setea donde mira el lapiz a default
    lapiz.pendown()
    lapiz.color("black")
    lapiz.circle(25)
    lapiz.left(-70)
    lapiz.forward(30)
    lapiz.left(-10)
    lapiz.forward(40)
    lapiz.left(270)
    lapiz.forward(50)
    lapiz.left(90)
    lapiz.forward(50)
    lapiz.backward(50)
    lapiz.right(90)
    lapiz.backward(50)
    lapiz.left(10)
    lapiz.forward(50)
    lapiz.left(50)
    lapiz.forward(50)
    lapiz.backward(50)
    lapiz.left(-50)
    lapiz.backward(50)
    lapiz.left(80)
    lapiz.backward(40)
    lapiz.right(120)
    lapiz.forward(60)
    lapiz.width(1)
    lapiz.color("pink") #escrituras de la ciudad
    lapiz.setheading(-90)
    lapiz.forward(20)
    lapiz.begin_fill()
    lapiz.left(90)
    lapiz.forward(20)
    lapiz.left(90)
    lapiz.forward(10)
    lapiz.left(90)
    lapiz.forward(40)
    lapiz.left(90)
    lapiz.forward(10)
    lapiz.left(90)
    lapiz.forward(10)
    lapiz.end_fill()

    lapiz.penup()
    lapiz.goto(250,160)
    lapiz.speed(2)
    lapiz.color("black")

    #dialogo
    lapiz.pendown()
    lapiz.write("Quieres esto?. . .", True, font=("arial", 10))
    lapiz.undo()
    #cuadro blanco para borrar
    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.speed(3)
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("SOLVE MY READLE!!!", True, font=("arial", 10))
    lapiz.undo()
    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(170,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("Tienes que adivinar la frace que estoy pensando...", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(170,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("Tienes 6 intentos", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("Sinó... pues", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("You y tu town say bye bye ", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    lapiz.penup()
    lapiz.color("black")
    lapiz.goto(250,160)
    lapiz.pendown()
    lapiz.speed(1)
    lapiz.write("MUAJAJAJAJAJA!!!!", True, font=("arial", 10))
    lapiz.undo()

    # lapiz.penup()
    # lapiz.goto(250,60)
    # lapiz.pendown()
    # lapiz.color("white")
    # lapiz.speed(0)
    # lapiz.write("█████████████████████████████████", True, font=("arial", 10))

    sherif_acepto_reto()

landscape()
intro_sherif()
animacion_ladron()

input() #para que no se cierre instantaneamente